/* autogenerated by Processing revision 1277 on 2022-12-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class index extends PApplet {

String filePath = "info.txt";
String[] lines;
String[] newLines;

 public void setup() {
  /* size commented out by preprocessor */;
  lines = loadStrings(filePath);
  printArray(lines);
  
  background(0);
  // Print the contents of the file to the console
  strokeWeight(1); 
  stroke(138,135,134,54);
  for(int i = 0; i < height; i += 20){
    line(0, i, width, i);
  }
  for(int j = 20; j < width; j += 20){
    line(j, 0, j, height);
  }

  stroke(255);
  frameRate(2);
  strokeWeight(5); 
}

char type;
int move,x,y;
int index; 

 public void draw() {
  translate(width/2, height/2);
  // for (int i = 0; i < lines.length; i++) {
    String[] pieces = split(lines[index], ' ');
    type = pieces[0].charAt(0);
    move = PApplet.parseInt(pieces[1]);

    
    // Convert the pieces of data to numbers
    switch(type){
      case 'U':
        y = move ;
       stroke(84,274,245, 90);
        break;
      case 'D':
        y = (move * -1) ;
      stroke(84,274,245, 90);
        break;
      case 'R':
        x = move ;
      stroke(255, 50);
        break;
      case 'L':
        x = (move * -1);
      stroke(255, 50);
    }
    if(index == 0){
      stroke(200,0,0);
    }

    // Draw a dot at the specified coordinates
    point(x * 20, y * 20);
    index++;
  // }

}


  public void settings() { size(1500, 900); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "index" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
